pipeline {
    agent any

    options {
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    stages {
        stage('Setup environemnt') {
            steps {
                sh 'echo "Setup env ..."'
                sh 'echo "empty folders.."'
            }
        }

        stage('Build') {
            environment {
                MY_NAME = "Maria"
            }
            steps {
                sh 'echo "Building ..."'
                sh 'echo "Name: $MY_NAME"'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Testing ..."'
            }
        }
    }

    post {
        success {
            sh 'echo "Success"'
        }
        failure {
            sh 'echo "Failure"'
        }
        always {
            sh 'echo "############## End ###################"'
        }
    }
}