pipeline {
    agent any

    options {
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    stages {
        stage('Setup environemnt') {
            steps {
                echo 'Setup env ...'
            }
        }

        stage('Build') {
            steps {
                echo 'Building ...'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing ...'
            }
        }
    }

    post {
        success {
            echo "Success"
        }
        failure {
            echo "Failure"
        }
        always {
            echo "############## End ###################"
        }
    }
}