pipeline{
    agent{
        label "master"
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }
    stages{
        stage("A"){
            steps{
                echo "========executing A========"
            }
        }
        stage("Simple Userinput"){
            steps{
                input message: "Continue to next stage?"
            }
        }
        stage("Message"){
            steps{
                input message: "Do you agree?", ok: "Yes, I agree", submitter: "jenkins,someotheruser"
            }
        }
        stage("Test for userinput with parameter") {
            steps{
                input
                    id: "branchname",
                    message: "Which branch?",
                    ok: "continue",
                    parameters: [string]
                
                echo "$branchname"
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}