pipeline{
    agent{
        label "master"
    }
    stages{
        stage("A"){
            steps{
                echo "========executing A========"
            }
        }
        stage("Simple Userinput"){
            steps{
                input "Continue to next stage?"
            }
        }
        stage("Message"){
            steps{
                message "This is a simple message."
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}